export const TN_ESTIMATIONS = 'estimations';

export const createTableQureyEstmations = `CREATE TABLE IF NOT EXISTS ${TN_ESTIMATIONS} (
  uuid TEXT PRIMARY KEY,
  id INTEGER UNIQUE,
  EstimationRequirement TEXT,
  CivilConstructedStarted TEXT,
  ShedLength TEXT,
  EquipementPlacementLength TEXT,
  ShedWidth TEXT,
  CShape TEXT,
  ModalType TEXT,
  SideWallColumnToColumnGap TEXT,
  NumberOfSheds TEXT,
  CurtainRequirment TEXT,
  DiselBrooderRequirment TEXT,
  PowerSupply TEXT,
  WaterSupply TEXT,
  Remarks TEXT,
  category TEXT,
  LeadDetail TEXT,
  sub_category TEXT,
  follow_up_date TEXT,
  closure_month TEXT,
  status TEXT,
  lastUpdatedBy TEXT,
  estimation_amount TEXT,
  estimationNumber TEXT,
  documents TEXT,
  ho_document TEXT,
  firm_farmer_name TEXT,
  Estimation_request_date TEXT,
  Estimation_generated_date TEXT,
  estimation_remarks TEXT,
  Ho_executive_id TEXT,
  Bdm_id TEXT,
  Is_downloadable INTEGER,
  Approval_from TEXT,
  last_estimation_number TEXT,
  createdAt TEXT,
  updatedAt TEXT,
  BDMId TEXT,
  LeadDetailId TEXT,
  LeadDetailUuid TEXT,
  is_active BOOLEAN DEFAULT 1
)`;