export const TN_LEADS = 'leads';

export const createTableQureyLeads = `CREATE TABLE IF NOT EXISTS ${TN_LEADS} (
  uuid TEXT PRIMARY KEY,
  id INTEGER UNIQUE,
  InquiryType TEXT,
  Project TEXT,
  CustomerName TEXT,
  MobileNo TEXT,
  AlternateMobileNo TEXT,
  WhatsappNo TEXT,
  CustomerMailId TEXT,
  pincode TEXT,
  state_name TEXT,
  region_name TEXT,
  location TEXT,
  site_location_address TEXT,
  call_status TEXT,
  call_type TEXT,
  category TEXT,
  sub_category TEXT,
  agent_remark TEXT,
  bdm_remark TEXT,
  follow_up_date TEXT,
  lead_transfer_date TEXT,
  source_of_lead_generated INTEGER,
  lead_owner TEXT,
  close_month TEXT,
  AgentId INTEGER,
  BDMId INTEGER,
  Campaign TEXT,
  Agent TEXT,
  BDM TEXT,
  SuperviserID INTEGER,
  lead_created_by INTEGER,
  last_action TEXT,
  created_by INTEGER,
  RegionId TEXT,
  categoryId INTEGER,
  subCategoryId INTEGER,
  branchName TEXT,
  branchId INTEGER,
  districtName TEXT,
  siteLocationAddress TEXT,
  createdAt TEXT,
  updatedAt TEXT,
  is_active BOOLEAN DEFAULT 1
);`;

